services:
  - type: web
    name: quess-corp-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        value: https://quess-corp-assesment.vercel.app
      - key: PYTHON_VERSION
        value: 3.11.0
